# Generated by Django 3.2.4 on 2021-06-25 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_rename_batch_warehousestock_productname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehousestock',
            old_name='productname',
            new_name='batch',
        ),
    ]
