# Generated by Django 3.2.4 on 2021-07-06 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_rename_productname_warehousestock_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousestock',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
