# Generated by Django 3.0.8 on 2021-09-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productsactive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('cleansing_mylk', models.IntegerField(default=0)),
                ('butter', models.IntegerField(default=0)),
                ('after_shave_mylk', models.IntegerField(default=0)),
                ('curd', models.IntegerField(default=0)),
                ('mayo', models.IntegerField(default=0)),
                ('mylk', models.IntegerField(default=0)),
                ('mylk_1L_Pack', models.IntegerField(default=0)),
                ('choc_mylk', models.IntegerField(default=0)),
                ('no_sugar_mylk', models.IntegerField(default=0)),
                ('no_sugar_mylk_1L_Pack', models.IntegerField(default=0)),
                ('cheese', models.IntegerField(default=0)),
                ('paneer', models.IntegerField(default=0)),
                ('thunder', models.IntegerField(default=0)),
                ('ranch', models.IntegerField(default=0)),
                ('parmesan', models.IntegerField(default=0)),
                ('shampoo_bar', models.IntegerField(default=0)),
            ],
        ),
    ]
