# Generated by Django 3.0.8 on 2022-02-07 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderprocessing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amzonproducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('contents', models.CharField(max_length=50)),
                ('pack', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('price', models.FloatField()),
            ],
        ),
    ]
