# Generated by Django 3.0.8 on 2022-02-07 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderprocessing', '0002_amzonproducts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box', models.CharField(max_length=5)),
                ('Height', models.FloatField()),
                ('Length', models.FloatField()),
                ('Width', models.FloatField()),
                ('mylk', models.IntegerField(default=0)),
                ('butter', models.IntegerField(default=0)),
                ('mayo', models.IntegerField(default=0)),
            ],
        ),
    ]
