# Generated by Django 3.0.8 on 2022-02-07 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderprocessing', '0003_box'),
    ]

    operations = [
        migrations.RenameField(
            model_name='box',
            old_name='box',
            new_name='Box',
        ),
    ]
