# Generated by Django 3.2.4 on 2021-06-12 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import reports.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Returnreports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateTimeField()),
                ('quantity', models.IntegerField()),
                ('comments', models.TextField(null=True)),
                ('type', models.CharField(max_length=10)),
                ('submission_date', models.DateTimeField()),
                ('batch_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.batch')),
                ('submitted_by', models.ForeignKey(on_delete=models.SET(reports.models.get_deleted_user_instance), to=settings.AUTH_USER_MODEL)),
                ('warehouse_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='Notdelivered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateTimeField()),
                ('order_id', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('reason', models.CharField(max_length=50)),
                ('comments', models.TextField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('batch_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.batch')),
                ('submitted_by', models.ForeignKey(on_delete=models.SET(reports.models.get_deleted_user_instance), to=settings.AUTH_USER_MODEL)),
                ('warehouse_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='Instock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateTimeField()),
                ('quantity', models.IntegerField()),
                ('comments', models.TextField(null=True)),
                ('submission_date', models.DateTimeField()),
                ('batch_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.batch')),
                ('submitted_by', models.ForeignKey(on_delete=models.SET(reports.models.get_deleted_user_instance), to=settings.AUTH_USER_MODEL)),
                ('warehouse_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateTimeField()),
                ('quantity', models.IntegerField()),
                ('comments', models.TextField(null=True)),
                ('type', models.CharField(max_length=10)),
                ('submission_date', models.DateTimeField()),
                ('batch_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.batch')),
                ('submitted_by', models.ForeignKey(on_delete=models.SET(reports.models.get_deleted_user_instance), to=settings.AUTH_USER_MODEL)),
                ('warehouse_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse')),
            ],
        ),
    ]
