# Generated by Django 3.2.4 on 2021-07-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='comments',
        ),
        migrations.AlterField(
            model_name='delivery',
            name='submission_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
