# Generated by Django 3.2.4 on 2021-07-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20210714_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instock',
            name='comments',
        ),
        migrations.AlterField(
            model_name='instock',
            name='submission_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
