# Generated by Django 3.2.4 on 2021-07-14 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20210714_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notdelivered',
            name='comments',
        ),
    ]
