# Generated by Django 3.2.4 on 2021-07-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_remove_notdelivered_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnreports',
            name='comments',
        ),
        migrations.AlterField(
            model_name='returnreports',
            name='submission_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
