# Generated by Django 3.2.4 on 2021-06-12 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=100)),
                ('is_active', models.BooleanField()),
                ('pub_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50)),
                ('manufacture_date', models.DateTimeField()),
                ('quantity', models.IntegerField()),
                ('comments', models.TextField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('productname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('submitted_by', models.ForeignKey(on_delete=models.SET(products.models.get_deleted_user_instance), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
