# Generated by Django 3.2.4 on 2021-06-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='current_stock',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
