# Generated by Django 3.2.4 on 2021-07-21 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_batch_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='current_stock',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='last_updated',
        ),
    ]
